---
kind: pipeline
name: arm

platform:
  os: linux
  arch: arm

workspace:
  base: /go
  path: src/github.com/snapcore/snapd

steps:
- name: version
  image: syncloud/build-deps-arm
  commands:
  - echo $(date +%y%m%d)$DRONE_BUILD_NUMBER > version

- name: build
  image: syncloud/build-deps-arm
  commands:
  - VERSION=$(cat version)
  - "./syncloud/build.sh $VERSION skip-tests "

- name: test
  image: syncloud/build-deps-arm
  commands:
  - VERSION=$(cat version)
  - ./syncloud/test.sh $VERSION device

- name: upload
  image: syncloud/build-deps-arm
  commands:
  - VERSION=$(cat version)
  - pip2 install -r dev_requirements.txt
  - syncloud-upload.sh snapd $DRONE_BRANCH $VERSION snapd-$VERSION-$(dpkg-architecture -q DEB_HOST_ARCH).tar.gz
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    key:
      from_secret: artifact_key
    source: syncloud/log/*
    strip_components: 2
    target: /home/artifact/repo/snapd/${DRONE_BUILD_NUMBER}-arm
    timeout: 2m
    username: artifact
  when:
    status:
    - failure
    - success

services:
- name: device
  image: syncloud/systemd-arm
  privileged: true
  volumes:
  - name: dbus
    path: /var/run/dbus
  - name: dev
    path: /dev

volumes:
- name: dbus
  host:
    path: /var/run/dbus
- name: dev
  host:
    path: /dev
- name: shm
  temp: {}

---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/snapcore/snapd

steps:
- name: version
  image: syncloud/build-deps-amd64
  commands:
  - echo $(date +%y%m%d)$DRONE_BUILD_NUMBER > version

- name: build
  image: syncloud/build-deps-amd64
  commands:
  - VERSION=$(cat version)
  - "./syncloud/build.sh $VERSION skip-tests "

- name: test
  image: syncloud/build-deps-amd64
  commands:
  - VERSION=$(cat version)
  - ./syncloud/test.sh $VERSION device

- name: upload
  image: syncloud/build-deps-amd64
  commands:
  - VERSION=$(cat version)
  - pip2 install -r dev_requirements.txt
  - syncloud-upload.sh snapd $DRONE_BRANCH $VERSION snapd-$VERSION-$(dpkg-architecture -q DEB_HOST_ARCH).tar.gz
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    key:
      from_secret: artifact_key
    source: syncloud/log/*
    strip_components: 2
    target: /home/artifact/repo/snapd/${DRONE_BUILD_NUMBER}-amd64
    timeout: 2m
    username: artifact
  when:
    status:
    - failure
    - success

services:
- name: device
  image: syncloud/systemd-amd64
  privileged: true
  volumes:
  - name: dbus
    path: /var/run/dbus
  - name: dev
    path: /dev

volumes:
- name: dbus
  host:
    path: /var/run/dbus
- name: dev
  host:
    path: /dev
- name: shm
  temp: {}

...
